### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cedrick-f** [cedrick-f/labyrinthe#1]
- [x] Ouvrir les murs vers l'extérieur (ouvertures) après construction, ou marquer les cellules de départ et d'arrivée
- [x] Marquer les cellules de départ et d'arrivée avant résolution automatique
- [ ] Ajouter score (temps, nombre de cellules visitées, nombre de mouvements réalisés, ...) après résolution manuelle
- [ ] Ajouter information sur l'algorithme de résolution
- [ ] Trouver un meilleur emplacement pour chrono (et autres "statistiques) pendant résolution manuelle
- [x] Terminer Prim
- [x] Ajouter algo construction par division récursive
- [ ] Ajouter import/export labytinthe
- [ ] Ajouter Wall Of Fame
